(()=>{'use strict';
 const $=id=>document.getElementById(id),C=ShogiSchoolCore,E=createShogiEngine({allowMissingKing:true}),copy=C.copy,pos=i=>'９８７６５４３２１'[i%9]+'一二三四五六七八九'[Math.floor(i/9)];
 let library={version:1,revision:0,items:[]},draft,side=1,held=null,selected=null,dirty=false,verified=null,verifying=false,busy=false,play=null,timer=null,answer=null,answerIndex=0,confirmAction=null,ready=false,history=[],historyIndex=0,placed=null;
 const rpc=(fn,...args)=>new Promise((resolve,reject)=>{if(!window.google?.script?.run){reject(Error('保存にはGoogleドライブへの接続が必要です。'));return;}google.script.run.withSuccessHandler(resolve).withFailureHandler(e=>reject(Error(e.message||'Googleドライブに接続できませんでした。')))[fn](...args);});
 const fields=()=>({...draft,title:$('problem-title').value,depth:Number($('problem-depth').value),hint:$('problem-hint').value,lesson:$('problem-lesson').value});
 const signature=q=>JSON.stringify([q.depth,q.pieces,q.hand]);
 const status=(text,error=false)=>{$('verify-status').textContent=text;$('verify-status').classList.toggle('error',error);};
 const ask=(title,text,action)=>{confirmAction=action;$('confirm-title').textContent=title;$('confirm-copy').textContent=text;$('confirm-dialog').showModal();paintCursor();};
 const unsaved=action=>dirty?ask('変更を破棄しますか？','保存していない変更があります。今の編集内容を破棄して進みます。',action):action();
 $('confirm-ok').onclick=()=>{const fn=confirmAction;confirmAction=null;$('confirm-dialog').close();fn?.();syncCursor();};$('confirm-cancel').onclick=()=>{$('confirm-dialog').close();syncCursor();};
 const snapshot=()=>copy({pieces:draft.pieces,hand:draft.hand});
 function changed(){dirty=true;verified=null;status('');$('draft-status').textContent='未保存の変更';}
 function open(q){clearTimeout(timer);play=null;answer=null;held=null;placed=null;document.body.dataset.playing='false';draft=copy(q);dirty=false;verified=null;selected=null;history=[snapshot()];historyIndex=0;$('problem-title').value=q.title;$('problem-depth').value=q.depth;$('problem-hint').value=q.hint;$('problem-lesson').value=q.lesson;$('library').value=library.items.some(x=>x.id===q.id)?q.id:'';$('board-status').textContent='';status('');render();}
 function blank(){return {id:null,title:'',depth:1,pieces:[],hand:[],hint:'',lesson:''};}
 function renderLibrary(){const select=$('library');select.replaceChildren(new Option('新しい問題',''));for(const q of library.items)select.add(new Option(q.title+' · '+q.depth+'手詰',q.id));$('saved-count').textContent=library.items.length+' / 10問';if(draft)select.value=draft.id||'';}
 function boardData(){return play?play.state.board:Array.from({length:81},(_,i)=>draft.pieces.find(p=>p[0]===i)?.[1]||0);}
 function pieceNode(p){const span=document.createElement('span');span.className='piece school-piece'+(p<0?' enemy':'')+(Math.abs(p)>8?' promoted':'');span.textContent=E.NAMES[Math.abs(p)];return span;}
 function commit(next,message,square=null){
  const before=JSON.stringify(snapshot()),after=JSON.stringify({pieces:next.pieces,hand:next.hand});held=null;selected=null;
  if(before!==after){draft.pieces=next.pieces;draft.hand=next.hand;history=history.slice(0,historyIndex+1);history.push(snapshot());if(history.length>81)history.shift();historyIndex=history.length-1;changed();}
  placed=square;$('board-status').textContent=message;render();
 }
 function drop(target){if(!held||play)return;try{const q=C.place(draft,held,target);commit(q,target==='hand'?'持ち駒に置きました。':target==='box'?'駒箱に戻しました。':pos(target)+'に置きました。',Number.isInteger(target)?target:null);}catch(e){status(e.message,true);}}
 function cancelCarry(){held=null;selected=null;render();}
 function moveHistory(delta){if(play||historyIndex+delta<0||historyIndex+delta>=history.length)return;historyIndex+=delta;Object.assign(draft,copy(history[historyIndex]));held=null;placed=null;changed();$('board-status').textContent=delta<0?'配置を一つ戻しました。':'配置をやり直しました。';render();}
 function render(){
  const b=boardData(),moves=play&&play.state.turn===1&&!play.over&&!answer?E.legalMoves(play.state):[],targets=selected!==null?moves.filter(m=>typeof selected==='object'?m.drop===selected.drop:m.from===selected).map(m=>m.to):[];
  $('school-board').replaceChildren();b.forEach((p,i)=>{
   const origin=play?selected===i:held?.source==='board'&&held.from===i;
   const btn=document.createElement('button');btn.type='button';btn.className='cell school-cell'+(origin?' selected held-origin':'')+(targets.includes(i)?' legal':'')+((play?.state.last?.to===i||(!play&&placed===i))?' last':'')+(!play&&placed===i?' just-placed':'');btn.dataset.square=i;btn.setAttribute('aria-label',pos(i)+' '+(p?(p>0?'自分の':'相手の')+E.FULL_NAMES[Math.abs(p)]:'空きマス'));if(p)btn.append(pieceNode(p));btn.onclick=()=>square(i);$('school-board').append(btn);
  });
  $('side-own').setAttribute('aria-pressed',side===1);$('side-enemy').setAttribute('aria-pressed',side===-1);$('palette').replaceChildren();
  for(const t of [1,2,3,4,5,6,7,8]){
   const pt=$('promoted').checked&&[1,2,3,4,6,7].includes(t)?t+8:t,p=side*pt,left=C.remaining(draft,p),button=document.createElement('button');button.append(pieceNode(p));const n=document.createElement('small');n.textContent=left;n.setAttribute('aria-hidden','true');button.append(n);button.setAttribute('aria-label',E.FULL_NAMES[pt]+'を駒箱から選ぶ（残り'+left+'枚）');button.title=E.FULL_NAMES[pt];button.setAttribute('aria-pressed',held?.source==='palette'&&held.piece===p);button.disabled=left<1;button.onclick=()=>{held=held?.source==='palette'&&held.piece===p?null:{source:'palette',piece:p};selected=null;placed=null;render();};$('palette').append(button);
  }
  $('school-hand').replaceChildren();const counts=play?play.state.hands[0]:Array.from({length:8},(_,t)=>draft.hand.filter(x=>x===t).length);
  for(let t=1;t<=7;t++)if(counts[t]){
   const btn=document.createElement('button');btn.className='hand-piece';btn.append(pieceNode(t));const n=document.createElement('small');n.textContent=counts[t];btn.append(n);btn.setAttribute('aria-label','持ち駒の'+E.FULL_NAMES[t]);btn.classList.toggle('selected',play?selected?.drop===t:held?.source==='hand'&&C.baseType(held.piece)===t);btn.classList.toggle('held-origin',!play&&held?.source==='hand'&&C.baseType(held.piece)===t);btn.onclick=()=>{if(play){if(play.state.turn!==1||play.over||answer)return;selected=selected?.drop===t?null:{drop:t};}else{held=held?.source==='hand'&&C.baseType(held.piece)===t?null:{source:'hand',piece:t};}render();};$('school-hand').append(btn);
  }
  if(!counts.some(Boolean)){const empty=document.createElement('span');empty.className='empty-note';empty.textContent=play?'持ち駒なし':'持ち上げた駒を、ここに置けます';$('school-hand').append(empty);}
  $('add-hand').hidden=Boolean(play);$('add-hand').disabled=!held||C.baseType(held.piece)===8;$('hand-tray').classList.toggle('can-drop',Boolean(held&&C.baseType(held.piece)!==8));$('play-controls').hidden=!play;$('answer-controls').hidden=!answer;$('board-mode').textContent=play?(answer?'答えと解説':'試しに解く'):'盤面を編集';
  $('selection-note').textContent=held?(held.piece>0?'自分の':'相手の')+E.FULL_NAMES[Math.abs(held.piece)]+'を持っています · 置きたいマスをクリック':'駒箱や盤の駒をクリックして持ち上げます。';
  $('flip-piece').disabled=!held;$('promote-piece').disabled=!held||[5,8].includes(C.baseType(held.piece));$('erase-tool').disabled=!held||held.source==='palette';$('cancel-carry').disabled=!held;$('edit-undo').disabled=historyIndex===0;$('edit-redo').disabled=historyIndex===history.length-1;
  $('save').disabled=busy||!ready;$('delete').disabled=busy||!ready||!library.items.some(q=>q.id===draft.id);$('verify').disabled=verifying;$('try-play').disabled=verifying;for(const id of ['new','sample','library','reload'])$(id).disabled=busy||verifying;
  $('draft-status').textContent=dirty?'未保存の変更':library.items.some(q=>q.id===draft.id)?'保存済み':'未保存';if(!play)$('play-explanation').hidden=true;syncCursor();
 }
 function square(i){if(play){playSquare(i);return;}if(held){if(held.source==='board'&&held.from===i&&boardData()[i]===held.piece){cancelCarry();return;}drop(i);}else{const p=boardData()[i];if(p){held={source:'board',piece:p,original:p,from:i};placed=null;render();}}}
 $('side-own').onclick=()=>{side=1;if(held?.source==='palette')held.piece=Math.abs(held.piece);render();};$('side-enemy').onclick=()=>{side=-1;if(held?.source==='palette')held.piece=-Math.abs(held.piece);render();};
 $('promoted').onchange=()=>{if(held?.source==='palette'){const t=C.baseType(held.piece);held.piece=side*(t+($('promoted').checked&&[1,2,3,4,6,7].includes(t)?8:0));}render();};
 $('flip-piece').onclick=()=>{if(held){held.piece=-held.piece;render();}};$('promote-piece').onclick=()=>{if(held&&![5,8].includes(C.baseType(held.piece))){const p=held.piece;held.piece=Math.sign(p)*(Math.abs(p)>8?Math.abs(p)-8:Math.abs(p)+8);render();}};
 $('cancel-carry').onclick=cancelCarry;$('erase-tool').onclick=()=>drop('box');$('add-hand').onclick=()=>drop('hand');$('hand-tray').onclick=e=>{if(held&&!play&&!e.target.closest('button'))drop('hand');};$('edit-undo').onclick=()=>moveHistory(-1);$('edit-redo').onclick=()=>moveHistory(1);
 $('clear-board').onclick=()=>ask('盤を空にしますか？','盤上の駒と持ち駒を駒箱に戻します。「戻す」で直前の配置に戻せます。',()=>commit({...draft,pieces:[],hand:[]},'盤を空にしました。'));
 for(const id of ['problem-title','problem-hint','problem-lesson'])$(id).oninput=()=>{dirty=true;$('draft-status').textContent='未保存の変更';};$('problem-depth').onchange=changed;
 const cursor=document.createElement('div');cursor.id='creator-cursor';cursor.hidden=true;cursor.setAttribute('aria-hidden','true');document.body.append(cursor);
 const pointer={x:0,y:0,inside:false,mouse:false};let cursorFrame=0,hovered=null;
 function carriedPiece(){return play?(selected!==null&&!play.over&&!answer?(typeof selected==='object'?selected.drop:play.state.board[selected]):0):held?.piece||0;}
 function paintCursor(){cursorFrame=0;const active=Boolean(carriedPiece()&&pointer.mouse&&pointer.inside&&!document.querySelector('dialog[open]'));cursor.hidden=!active;document.body.classList.toggle('creator-carrying',active);hovered?.classList.remove('drop-hover');hovered=null;if(!active)return;cursor.style.transform='translate3d('+pointer.x+'px,'+pointer.y+'px,0) translate(-50%,-62%)';const cell=document.elementFromPoint(pointer.x,pointer.y)?.closest('.school-cell');if(cell&&(!play||cell.classList.contains('legal'))){cell.classList.add('drop-hover');hovered=cell;}}
 function syncCursor(){const p=carriedPiece();if(p){cursor.replaceChildren(pieceNode(p));const cell=$('school-board').querySelector('.school-cell'),piece=$('school-board').querySelector('.piece');if(cell){const r=cell.getBoundingClientRect();cursor.style.width=r.width*.83+'px';cursor.style.height=r.height*.91+'px';}if(piece)cursor.style.setProperty('--carried-font',getComputedStyle(piece).fontSize);}paintCursor();}
 function trackPointer(e){pointer.x=e.clientX;pointer.y=e.clientY;pointer.inside=true;pointer.mouse=e.pointerType==='mouse'||e.pointerType==='pen';if(carriedPiece()&&!cursorFrame)cursorFrame=requestAnimationFrame(paintCursor);}
 document.addEventListener('pointermove',trackPointer,{passive:true});document.addEventListener('pointerdown',trackPointer,{passive:true,capture:true});document.addEventListener('pointerleave',()=>{pointer.inside=false;paintCursor();});window.addEventListener('blur',()=>{pointer.inside=false;paintCursor();});window.addEventListener('resize',syncCursor);window.addEventListener('scroll',()=>{if(carriedPiece())paintCursor();},{passive:true,capture:true});
 document.addEventListener('contextmenu',e=>{if(carriedPiece()&&!document.querySelector('dialog[open]')){e.preventDefault();cancelCarry();}});
 document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select')||document.querySelector('dialog[open]'))return;if(e.key==='Escape'&&carriedPiece()){e.preventDefault();cancelCarry();}else if(!play&&(e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();moveHistory(e.shiftKey?1:-1);}else if(!play&&held&&(e.key==='Delete'||e.key==='Backspace')){e.preventDefault();drop('box');}});
 document.addEventListener('click',e=>{if(carriedPiece()&&!document.querySelector('dialog[open]')&&!e.target.closest('#school-board,#school-hand,#palette,#carry-actions,.side-switch,.promote-toggle,#hand-tray')){held=null;selected=null;render();}},{capture:true});
 async function verify(){const q=fields(),key=signature(q);if(verified?.key===key)return verified.puzzle;verifying=true;status('玉の逃げ方と、別の正解がないかを調べています…');render();
  try{C.clean(q);const result=await new Promise((resolve,reject)=>{let url;if(window.SCHOOL_WORKER_SOURCE)url=URL.createObjectURL(new Blob([window.SCHOOL_WORKER_SOURCE],{type:'text/javascript'}));const worker=new Worker(url||'solver-worker.js');const deadline=setTimeout(()=>{worker.terminate();if(url)URL.revokeObjectURL(url);reject(Error('確認に時間がかかっています。駒を減らして再度確認してください。'));},18000);const end=()=>{clearTimeout(deadline);worker.terminate();if(url)URL.revokeObjectURL(url);};worker.onmessage=e=>{end();e.data.ok?resolve(e.data):reject(Error(e.data.error));};worker.onerror=()=>{end();reject(Error('確認を開始できませんでした。ページを開き直してください。'));};worker.postMessage(q);});
   if(signature(fields())!==key){status('確認中に配置が変わりました。もう一度確認してください。');return null;}const p={...q,...result};verified={key,puzzle:p};status(q.depth+'手詰です。正解の手順が一つであることを確認しました。');return p;
  }catch(e){status(e.message,true);return null;}finally{verifying=false;render();}
 }
 $('verify').onclick=verify;
 async function load(){busy=true;render();try{const data=await rpc('getLibrary');library=data.library;ready=true;renderLibrary();$('storage-status').textContent='Googleドライブに保存 · 保存した問題は自分だけが見られます';$('storage-status').classList.remove('error');$('drive-folder').href=data.folderUrl;$('drive-folder').hidden=false;}catch(e){ready=false;$('storage-status').textContent=e.message;$('storage-status').classList.toggle('error',Boolean(window.google?.script?.run));if(!window.google?.script?.run){const a=document.createElement('a');a.href='https://script.google.com/macros/s/AKfycbyKrZH1NFLY7WQRr3n3oBF-FQ9c5rxRsoY7ybPRa_ZXduwVXoyGb7knVCk_8dW6wAG_/exec';a.target='_top';a.textContent='Googleドライブに接続して保存';$('storage-status').append(a);}}finally{busy=false;render();}}
 $('reload').onclick=()=>unsaved(async()=>{const id=draft.id;await load();if(ready)open(library.items.find(q=>q.id===id)||blank());});$('library').onchange=()=>{const id=$('library').value;$('library').value=draft.id||'';unsaved(()=>open(library.items.find(q=>q.id===id)||blank()));};$('new').onclick=()=>unsaved(()=>open(blank()));$('sample').onclick=()=>unsaved(()=>{const q=C.sample();q.id=null;open(q);dirty=true;status('サンプルを読み込みました。保存すると自分の問題として登録できます。');});
 $('save').onclick=async()=>{const q=fields();try{C.clean(q);}catch(e){status(e.message,true);return;}busy=true;render();const fingerprint=JSON.stringify(q);try{const data=await rpc('savePuzzle',q,library.revision);library=data.library;draft.id=data.id;renderLibrary();if(JSON.stringify({...fields(),id:q.id})===fingerprint)dirty=false;$('library').value=data.id;status('Googleドライブに保存しました。');}catch(e){status(e.message,true);}finally{busy=false;render();}};
 $('delete').onclick=()=>ask('この問題を削除しますか？','Googleドライブの問題一覧から削除します。',async()=>{busy=true;render();try{const data=await rpc('deletePuzzle',draft.id,library.revision);library=data.library;renderLibrary();open(blank());status('問題を削除しました。');}catch(e){status(e.message,true);}finally{busy=false;render();}});
 function begin(p){clearTimeout(timer);held=null;play={puzzle:{...p,...fields()},state:copy(p.initial),over:false,mistake:false};answer=null;selected=null;document.body.dataset.playing='true';$('board-status').textContent='王手を続けて、'+p.depth+'手で詰ませましょう。';$('play-explanation').hidden=true;render();}
 $('try-play').onclick=async()=>{const p=await verify();if(p)begin(p);};$('play-retry').onclick=()=>begin(play.puzzle);$('play-back').onclick=()=>{clearTimeout(timer);play=null;answer=null;selected=null;document.body.dataset.playing='false';render();};
 let promotionMoves=[];function playSquare(i){if(play.state.turn!==1||play.over||answer)return;const b=play.state.board,moves=E.legalMoves(play.state);if(b[i]>0){selected=selected===i?null:i;render();return;}if(selected===null)return;const candidates=moves.filter(m=>m.to===i&&(typeof selected==='object'?m.drop===selected.drop:m.from===selected));if(!candidates.length)return;if(candidates.length>1){promotionMoves=candidates;$('school-promotion').showModal();paintCursor();}else applyUser(candidates[0]);}
 $('promote-yes').onclick=()=>{$('school-promotion').close();applyUser(promotionMoves.find(m=>m.promote));};$('promote-no').onclick=()=>{$('school-promotion').close();applyUser(promotionMoves.find(m=>!m.promote));};$('promote-cancel').onclick=()=>{$('school-promotion').close();syncCursor();};
 function finish(success){play.over=true;selected=null;$('board-status').textContent=success?'正解です！ '+play.state.ply+'手で詰みました。':'この手順では詰みませんでした。逃げ道を見て、もう一度試しましょう。';$('play-explanation').textContent=success?(fields().lesson||'玉は逃げられず、王手の駒を取ることも、間に駒を置くこともできません。'): '「答えを見る」で、正解の一手と比べてみましょう。';$('play-explanation').hidden=false;render();}
 function applyUser(m){if(!m)return;const wins=play.puzzle.proof[E.key(play.state)]?.wins||[];play.mistake ||= !wins.some(w=>w.to===m.to&&w.from===m.from&&w.drop===m.drop&&Boolean(w.promote)===Boolean(m.promote));selected=null;play.state=E.play(play.state,m);play.mistake ||= !E.inCheck(play.state,-1);render();const moves=E.legalMoves(play.state);if(E.inCheck(play.state,-1)&&!moves.length){finish(!play.mistake);return;}if(play.state.ply>=play.puzzle.depth||!moves.length){finish(false);return;}$('board-status').textContent='相手が考えています…';const session=play;timer=setTimeout(()=>{if(play!==session)return;const node=play.puzzle.proof[E.key(play.state)],reply=node?.reply||E.chooseMove(play.state,{budgetMs:80,random:()=>0});if(!reply){finish(false);return;}play.state=E.play(play.state,reply);render();if(play.state.ply>=play.puzzle.depth||!E.legalMoves(play.state).length)finish(false);else $('board-status').textContent='あなたの番です · '+play.state.ply+' / '+play.puzzle.depth+'手';},650);}
 function drawAnswer(){const step=answer[answerIndex];play.state=copy(step.state);$('answer-step').textContent=answerIndex+' / '+(answer.length-1)+' 手';$('answer-prev').disabled=answerIndex===0;$('answer-next').disabled=answerIndex===answer.length-1;$('board-status').textContent=step.text;$('play-explanation').textContent=fields().lesson||'王手の駒を支える仲間と、玉の逃げ道を見比べてみましょう。';$('play-explanation').hidden=false;render();}
 $('play-answer').onclick=()=>{clearTimeout(timer);play.over=true;let s=copy(play.puzzle.initial);answer=[{state:s,text:'最初の配置です。'}];for(let d=0;d<play.puzzle.depth;d++){const n=play.puzzle.proof[E.key(s)],m=s.turn===1?n?.wins?.[0]:n?.reply;if(!m)break;const text=(s.turn===1?'自分：':'相手：')+pos(m.to)+E.FULL_NAMES[m.drop||Math.abs(s.board[m.from])]+(m.drop?'を打ちます':m.promote?'を動かして成ります':'を動かします');s=E.play(s,m);answer.push({state:s,text});}answerIndex=0;drawAnswer();};$('answer-prev').onclick=()=>{if(answerIndex>0){answerIndex--;drawAnswer();}};$('answer-next').onclick=()=>{if(answerIndex<answer.length-1){answerIndex++;drawAnswer();}};
 $('play-hint').onclick=()=>{$('play-explanation').textContent=play.puzzle.hint||'王手になる置き方と、玉の逃げ道を見比べてみましょう。';$('play-explanation').hidden=false;};$('how-button').onclick=()=>{$('how-dialog').showModal();paintCursor();};$('how-close').onclick=()=>{$('how-dialog').close();syncCursor();};$('school-files').innerHTML=[...'９８７６５４３２１'].map(x=>'<span>'+x+'</span>').join('');$('school-ranks').innerHTML=[...'一二三四五六七八九'].map(x=>'<span>'+x+'</span>').join('');window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});open(blank());load();
})();
