(()=>{'use strict';
 const $=id=>document.getElementById(id),C=ShogiSchoolCore,E=createShogiEngine({allowMissingKing:true}),copy=C.copy,pos=i=>'９８７６５４３２１'[i%9]+'一二三四五六七八九'[Math.floor(i/9)];
 let library={version:1,revision:0,items:[]},draft,side=1,type=5,tool='place',selected=null,dirty=false,verified=null,verifying=false,busy=false,play=null,timer=null,answer=null,answerIndex=0,confirmAction=null,ready=false;
 const rpc=(fn,...args)=>new Promise((resolve,reject)=>{if(!window.google?.script?.run){reject(Error('保存にはGoogleドライブ版のスクールを開いてください。'));return;}google.script.run.withSuccessHandler(resolve).withFailureHandler(e=>reject(Error(e.message||'Googleドライブに接続できませんでした。')))[fn](...args);});
 const fields=()=>({...draft,title:$('problem-title').value,depth:Number($('problem-depth').value),hint:$('problem-hint').value,lesson:$('problem-lesson').value});
 const signature=q=>JSON.stringify([q.depth,q.pieces,q.hand]);
 const status=(text,error=false)=>{$('verify-status').textContent=text;$('verify-status').classList.toggle('error',error);};
 const ask=(title,text,action)=>{confirmAction=action;$('confirm-title').textContent=title;$('confirm-copy').textContent=text;$('confirm-dialog').showModal();};
 const unsaved=action=>dirty?ask('変更を破棄しますか？','保存していない変更があります。今の編集内容を破棄して進みます。',action):action();
 $('confirm-ok').onclick=()=>{const fn=confirmAction;confirmAction=null;$('confirm-dialog').close();fn?.();};$('confirm-cancel').onclick=()=>$('confirm-dialog').close();
 function changed(){dirty=true;verified=null;status('配置を変えたら、もう一度詰みを確認しましょう。');}
 function open(q){clearTimeout(timer);play=null;answer=null;document.body.dataset.playing='false';draft=copy(q);dirty=false;verified=null;selected=null;tool='place';$('problem-title').value=q.title;$('problem-depth').value=q.depth;$('problem-hint').value=q.hint;$('problem-lesson').value=q.lesson;$('library').value=library.items.some(x=>x.id===q.id)?q.id:'';status('');render();}
 function blank(){return {id:null,title:'',depth:1,pieces:[],hand:[],hint:'',lesson:''};}
 function renderLibrary(){const select=$('library');select.replaceChildren(new Option('新しい問題',''));for(const q of library.items)select.add(new Option(q.title+' · '+q.depth+'手詰',q.id));$('saved-count').textContent=library.items.length+' / 10問';if(draft)select.value=draft.id||'';}
 function boardData(){return play?play.state.board:Array.from({length:81},(_,i)=>draft.pieces.find(p=>p[0]===i)?.[1]||0);}
 function pieceNode(p){const span=document.createElement('span');span.className='school-piece'+(p<0?' enemy':'')+(Math.abs(p)>8?' promoted':'');span.textContent=E.NAMES[Math.abs(p)];return span;}
 function setSquare(i,p){draft.pieces=draft.pieces.filter(pair=>pair[0]!==i);if(p)draft.pieces.push([i,p]);changed();}
 function render(){
  const b=boardData(),moves=play&&play.state.turn===1&&!play.over&&!answer?E.legalMoves(play.state):[],targets=selected!==null?moves.filter(m=>typeof selected==='object'?m.drop===selected.drop:m.from===selected).map(m=>m.to):[];
  $('school-board').replaceChildren();b.forEach((p,i)=>{const btn=document.createElement('button');btn.type='button';btn.className='school-cell'+(i===selected?' selected':'')+(targets.includes(i)?' legal':'')+(play?.state.last?.to===i?' last':'');btn.dataset.square=i;btn.setAttribute('aria-label',pos(i)+' '+(p?(p>0?'自分の':'相手の')+E.FULL_NAMES[Math.abs(p)]:'空きマス'));if(p)btn.append(pieceNode(p));btn.onclick=()=>square(i);$('school-board').append(btn);});
  $('side-own').setAttribute('aria-pressed',side===1);$('side-enemy').setAttribute('aria-pressed',side===-1);$('move-tool').setAttribute('aria-pressed',tool==='move');$('erase-tool').setAttribute('aria-pressed',tool==='erase');$('palette').replaceChildren();
  for(const t of [1,2,3,4,5,6,7,8]){const pt=$('promoted').checked&&[1,2,3,4,6,7].includes(t)?t+8:t,button=document.createElement('button');button.textContent=E.NAMES[pt];button.setAttribute('aria-label',E.FULL_NAMES[pt]);button.setAttribute('aria-pressed',type===t&&tool==='place');button.onclick=()=>{type=t;tool='place';selected=null;render();};$('palette').append(button);}
  $('school-hand').replaceChildren();const counts=play?play.state.hands[0]:Array.from({length:8},(_,t)=>draft.hand.filter(x=>x===t).length);
  for(let t=1;t<=7;t++)if(counts[t]){const chip=document.createElement('span');chip.className='hand-chip';const btn=document.createElement('button');btn.textContent=E.FULL_NAMES[t]+' '+counts[t];btn.setAttribute('aria-label','持ち駒の'+E.FULL_NAMES[t]);btn.onclick=()=>{if(play){if(play.state.turn!==1||play.over||answer)return;selected={drop:t};render();}else{type=t;tool='place';render();}};chip.append(btn);if(!play){const minus=document.createElement('button');minus.textContent='−';minus.setAttribute('aria-label',E.FULL_NAMES[t]+'を持ち駒から1枚減らす');minus.onclick=()=>{draft.hand.splice(draft.hand.indexOf(t),1);changed();render();};chip.append(minus);}$('school-hand').append(chip);}
  $('add-hand').hidden=Boolean(play);$('play-controls').hidden=!play;$('answer-controls').hidden=!answer;$('board-mode').textContent=play?(answer?'答えと解説':'試しに解く'):'駒を並べる';$('selection-note').textContent=play?'':tool==='erase'?'消したい駒を押してください':tool==='move'?'元のマス → 移動先の順に押します':(side===1?'自分の':'相手の')+E.FULL_NAMES[$('promoted').checked&&[1,2,3,4,6,7].includes(type)?type+8:type]+'を置きます';
  $('save').disabled=busy||!ready;$('delete').disabled=busy||!ready||!library.items.some(q=>q.id===draft.id);$('verify').disabled=verifying;$('try-play').disabled=verifying; if(!play){$('board-status').textContent='相手の玉は下向き、自分の駒は上向きです。';$('play-explanation').hidden=true;}
 }
 function square(i){if(play){playSquare(i);return;}const b=boardData();if(tool==='erase'){setSquare(i,0);selected=null;}else if(tool==='move'){if(selected===null){if(b[i])selected=i;}else if(selected===i){selected=null;}else{const p=b[selected];setSquare(selected,0);setSquare(i,p);selected=null;}}else{const t=$('promoted').checked&&[1,2,3,4,6,7].includes(type)?type+8:type;setSquare(i,side*t);selected=i;}render();}
 $('side-own').onclick=()=>{side=1;render();};$('side-enemy').onclick=()=>{side=-1;render();};$('promoted').onchange=render;$('move-tool').onclick=()=>{tool='move';selected=null;render();};$('erase-tool').onclick=()=>{tool='erase';selected=null;render();};$('flip-piece').onclick=()=>{if(typeof selected==='number'&&boardData()[selected]){setSquare(selected,-boardData()[selected]);render();}else status('盤の駒を一つ選んでから押してください。',true);};
 $('clear-board').onclick=()=>ask('盤を空にしますか？','盤上の駒と持ち駒をすべて取り除きます。保存済みの問題はそのまま残ります。',()=>{draft.pieces=[];draft.hand=[];selected=null;changed();render();});$('add-hand').onclick=()=>{if(type===8){status('玉は持ち駒にできません。',true);return;}draft.hand.push(type);changed();render();};
 for(const id of ['problem-title','problem-hint','problem-lesson'])$(id).oninput=()=>{dirty=true;};$('problem-depth').onchange=changed;
 async function verify(){const q=fields(),key=signature(q);if(verified?.key===key)return verified.puzzle;verifying=true;status('玉の逃げ方と、別の正解がないかを調べています…');render();
  try{C.clean(q);const result=await new Promise((resolve,reject)=>{let url;if(window.SCHOOL_WORKER_SOURCE)url=URL.createObjectURL(new Blob([window.SCHOOL_WORKER_SOURCE],{type:'text/javascript'}));const worker=new Worker(url||'solver-worker.js');const deadline=setTimeout(()=>{worker.terminate();if(url)URL.revokeObjectURL(url);reject(Error('確認に時間がかかっています。駒を減らして再度確認してください。'));},18000);const end=()=>{clearTimeout(deadline);worker.terminate();if(url)URL.revokeObjectURL(url);};worker.onmessage=e=>{end();e.data.ok?resolve(e.data):reject(Error(e.data.error));};worker.onerror=()=>{end();reject(Error('確認を開始できませんでした。ページを開き直してください。'));};worker.postMessage(q);});
   if(signature(fields())!==key){status('確認中に配置が変わりました。もう一度確認してください。');return null;}const p={...q,...result};verified={key,puzzle:p};status(q.depth+'手詰です。正解の手順が一つであることを確認しました。');return p;
  }catch(e){status(e.message,true);return null;}finally{verifying=false;render();}
 }
 $('verify').onclick=verify;
 async function load(){busy=true;render();try{const data=await rpc('getLibrary');library=data.library;ready=true;renderLibrary();$('storage-status').textContent='Googleドライブに保存 · 保存した問題は自分だけが見られます';$('storage-status').classList.remove('error');$('drive-folder').href=data.folderUrl;$('drive-folder').hidden=false;}catch(e){ready=false;$('storage-status').textContent=e.message;$('storage-status').classList.add('error');if(!window.google?.script?.run){const a=document.createElement('a');a.href='https://script.google.com/macros/s/AKfycbyKrZH1NFLY7WQRr3n3oBF-FQ9c5rxRsoY7ybPRa_ZXduwVXoyGb7knVCk_8dW6wAG_/exec';a.target='_top';a.textContent=' Googleドライブ版を開く';$('storage-status').append(a);}}finally{busy=false;render();}}
 $('reload').onclick=()=>unsaved(async()=>{const id=draft.id;await load();if(ready)open(library.items.find(q=>q.id===id)||blank());});$('library').onchange=()=>{const id=$('library').value;$('library').value=draft.id||'';unsaved(()=>open(library.items.find(q=>q.id===id)||blank()));};$('new').onclick=()=>unsaved(()=>open(blank()));$('sample').onclick=()=>unsaved(()=>{const q=C.sample();q.id=null;open(q);dirty=true;status('サンプルを読み込みました。保存すると自分の問題として登録できます。');});
 $('save').onclick=async()=>{const q=fields();try{C.clean(q);}catch(e){status(e.message,true);return;}busy=true;render();const fingerprint=JSON.stringify(q);try{const data=await rpc('savePuzzle',q,library.revision);library=data.library;draft.id=data.id;renderLibrary();if(JSON.stringify({...fields(),id:q.id})===fingerprint)dirty=false;$('library').value=data.id;status('Googleドライブに保存しました。');}catch(e){status(e.message,true);}finally{busy=false;render();}};
 $('delete').onclick=()=>ask('この問題を削除しますか？','Googleドライブの問題一覧から削除します。',async()=>{busy=true;render();try{const data=await rpc('deletePuzzle',draft.id,library.revision);library=data.library;renderLibrary();open(blank());status('問題を削除しました。');}catch(e){status(e.message,true);}finally{busy=false;render();}});
 function begin(p){clearTimeout(timer);play={puzzle:{...p,...fields()},state:copy(p.initial),over:false};answer=null;selected=null;document.body.dataset.playing='true';$('board-status').textContent='王手を続けて、'+p.depth+'手で詰ませましょう。';$('play-explanation').hidden=true;render();}
 $('try-play').onclick=async()=>{const p=await verify();if(p)begin(p);};$('play-retry').onclick=()=>begin(play.puzzle);$('play-back').onclick=()=>{clearTimeout(timer);play=null;answer=null;selected=null;document.body.dataset.playing='false';render();};
 let promotionMoves=[];function playSquare(i){if(play.state.turn!==1||play.over||answer)return;const b=play.state.board,moves=E.legalMoves(play.state);if(b[i]>0){selected=selected===i?null:i;render();return;}if(selected===null)return;const candidates=moves.filter(m=>m.to===i&&(typeof selected==='object'?m.drop===selected.drop:m.from===selected));if(!candidates.length)return;if(candidates.length>1){promotionMoves=candidates;$('school-promotion').showModal();}else applyUser(candidates[0]);}
 $('promote-yes').onclick=()=>{$('school-promotion').close();applyUser(promotionMoves.find(m=>m.promote));};$('promote-no').onclick=()=>{$('school-promotion').close();applyUser(promotionMoves.find(m=>!m.promote));};$('promote-cancel').onclick=()=>$('school-promotion').close();
 function finish(success){play.over=true;selected=null;$('board-status').textContent=success?'正解です！ '+play.state.ply+'手で詰みました。':'この手順では詰みませんでした。逃げ道を見て、もう一度試しましょう。';$('play-explanation').textContent=success?(fields().lesson||'玉は逃げられず、王手の駒を取ることも、間に駒を置くこともできません。'): '「答えを見る」で、正解の一手と比べてみましょう。';$('play-explanation').hidden=false;render();}
 function applyUser(m){if(!m)return;selected=null;play.state=E.play(play.state,m);render();const moves=E.legalMoves(play.state);if(E.inCheck(play.state,-1)&&!moves.length){finish(true);return;}if(play.state.ply>=play.puzzle.depth||!moves.length){finish(false);return;}$('board-status').textContent='相手が考えています…';const session=play;timer=setTimeout(()=>{if(play!==session)return;const node=play.puzzle.proof[E.key(play.state)],reply=node?.reply||E.chooseMove(play.state,{budgetMs:80,random:()=>0});if(!reply){finish(false);return;}play.state=E.play(play.state,reply);render();if(play.state.ply>=play.puzzle.depth||!E.legalMoves(play.state).length)finish(false);else $('board-status').textContent='あなたの番です · '+play.state.ply+' / '+play.puzzle.depth+'手';},650);}
 function drawAnswer(){const step=answer[answerIndex];play.state=copy(step.state);$('answer-step').textContent=answerIndex+' / '+(answer.length-1)+' 手';$('answer-prev').disabled=answerIndex===0;$('answer-next').disabled=answerIndex===answer.length-1;$('board-status').textContent=step.text;$('play-explanation').textContent=fields().lesson||'王手の駒を支える仲間と、玉の逃げ道を見比べてみましょう。';$('play-explanation').hidden=false;render();}
 $('play-answer').onclick=()=>{clearTimeout(timer);play.over=true;let s=copy(play.puzzle.initial);answer=[{state:s,text:'最初の配置です。'}];for(let d=0;d<play.puzzle.depth;d++){const n=play.puzzle.proof[E.key(s)],m=s.turn===1?n?.wins?.[0]:n?.reply;if(!m)break;const text=(s.turn===1?'自分：':'相手：')+pos(m.to)+E.FULL_NAMES[m.drop||Math.abs(s.board[m.from])]+(m.drop?'を打ちます':m.promote?'を動かして成ります':'を動かします');s=E.play(s,m);answer.push({state:s,text});}answerIndex=0;drawAnswer();};$('answer-prev').onclick=()=>{if(answerIndex>0){answerIndex--;drawAnswer();}};$('answer-next').onclick=()=>{if(answerIndex<answer.length-1){answerIndex++;drawAnswer();}};
 $('how-button').onclick=()=>$('how-dialog').showModal();$('how-close').onclick=()=>$('how-dialog').close();$('school-files').innerHTML=[...'９８７６５４３２１'].map(x=>'<span>'+x+'</span>').join('');window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});open(blank());load();
})();
